Allow fileName option to be a function
relative-ci/rollup-plugin-webpack-stats pull request #256
Opened 2024-06-01 01:06 UTC by BPScott

By allowing the fileName to be a function that has access to the bundle that is being generated, we can generate multiple stats files with dynamic names.

This is particularly important when integrating with Vite's plugin-legacy to let you create stats for the legacy and modern bundles.

### But why allow access to `bundle`?

I'm using Vite and [`@vite/plugin-legacy`](https://www.npmjs.com/package/@vitejs/plugin-legacy) to create modern and legacy output in a single build. I'd like to use `rollup-plugin-webpack-stats` stats for both the modern and legacy bundles.

How `@vite/plugin-legacy` works is by essentially adding [a new rollup output](https://github.com/vitejs/vite/blob/147e9228bb1c75db153873761eb7a120a2bd09a4/packages/plugin-legacy/src/index.ts#L426-L438) that uses `format: 'systemjs'` to your existing build, copying the plugins and other options of any existing outputs.

By making the fileName a function that has access to bundle, I can add `webpackStats` to my Vite config like so, using the contents of the bundle to infer if I'm producing legacy or modern outputs:

```
import { defineConfig } from 'vite';
import { webpackStats } from 'rollup-plugin-webpack-stats';

export default {
  build: {
    rollupOptions: {
      output: {
        plugins: [
          webpackStats({
            fileName: (bundle) => {
              const isLegacy = Object.keys(bundle)
                .filter((item) => item.startsWith('assets/'))
                .every((item) => item.includes('-legacy-'));
              return `webpack-stats${isLegacy ? '-legacy' : '-modern'}.json`;
            },
          }),
        ]
      }
    }
  }
}
```

2024-06-03 18:16 UTC, vio requested changes
@BPScott Thank you for the PR! 

The code looks ok, happy to merge it. Only some minor suggestions on the README.md example just in case folks are copy-pasting the code.

2024-06-03 18:16 UTC, vio commented on README.md
> +          statsPlugin((options) => {
```suggestion
          webpackStats((outputOptions) => {
```

2024-06-03 18:16 UTC, vio commented on README.md
> +          // an addtional output, which duplicates the plugins configured here
```suggestion
          // an additional output, which duplicates the plugins configured here
```

2024-06-03 21:04 UTC, BPScott commented
Thanks for the review, I've updated the README

2024-06-03 22:16 UTC, vio approved these changes

2024-06-03 22:18 UTC, merged

2024-06-03 22:38 UTC, vio commented
Published on [`v0.3.0`](https://github.com/relative-ci/rollup-plugin-webpack-stats/releases/tag/v0.3.0).

Thanks again for the PR! 

Also, would really appreciate it if you could share how you are using the package. The package was created primarily to allow users to use [bundle-stats](https://github.com/relative-ci/bundle-stats) and [@relative-ci/agent](https://github.com/relative-ci/agent) with vite/rollup projects, if we manage to gather more info about the use cases, will help us when prioritizing and adding new features.

2024-06-04 00:36 UTC, BPScott commented
> Also, would really appreciate it if you could share how you are using the package. The package was created primarily to allow users to use [bundle-stats](https://github.com/relative-ci/bundle-stats) and [@relative-ci/agent](https://github.com/relative-ci/agent) with vite/rollup projects, if we manage to gather more info about the use cases, will help us when prioritizing and adding new features.


Using this package with Vite and using `bundle-stats` for analysis is exactly my team's use-case.

We're in the process of migrating our webpack application build process to use Vite. We currently perform webpack bundle analysis on a somewhat ad-hoc basis using [statoscope](https://github.com/statoscope/statoscope), but we're hoping to get better at automating this analysis and surfacing impact on PRs. I've been generally somewhat surprised at the lack of comparable bundle analysis tools for Rollup/Vite, so I was relieved to find `rollup-plugin-webpack-stats` and `bundle-stats`.

`rollup-plugin-webpack-stats` feels like a great solution to this problem space - porting data into a webpack-style stats file means being easily able to leverage existing analysis tools such as bundle-stats and statoscope - though I appreciate that focusing on making bundle-stats better is going to a much higher priority for you than stats file [completeness](https://webpack.js.org/api/stats/#root) to enable usage for other tools analysis tools.

A few questions that we tend to want to answer when doing build analysis:

Single builds:
- Where in our bundle is the majority of our file size?
- Are there any particular egregiously sized assets?
- Why is a file in a particular chunk? (what was a file's import chain)

Build comparisons:
- What files size impact did this change have, and in what chunk(s)? Ideally we'd be able to state something saying "Loading this URL results in loading the entry asset and these async assets" so we can get an idea of "amount of js/css required to load some particular URL - which is a sum of many assets.
- Did this PR cause files to move between chunks and if so, why?
- Did this PR introduce new package dependencies into the build?

2024-06-04 22:32 UTC, vio commented
Thank you for the detailed response, very insightful!

> though I appreciate that focusing on making bundle-stats better is going to a much higher priority for you than stats file [completeness](https://webpack.js.org/api/stats/#root) to enable usage for other tools analysis tools.

We didn't aim for complete parity, just to extract the data needed by bundle-stats. I think this is the case for most of the tools, they rely on a small percentage of the stats data. 

If it helps extract more data for other cases or tools, we are happy to accept PRs or implement the changes when we can ;)